### ISSUE TITLE
Crash on start up. Forge 14.23.3.2655

### ISSUE THREAD

**Issue by nitefang** [KaptainWutax/ImmersiveMusicMod#1]
Crashes on startup while initializing the mod.

Forge ver 14.23.3.2655
MC ver: 1.12.2
ImmersiveMusicMod ver: 0.0.2

Crash report: https://pastebin.com/3BXqrMbT

**Comment by KaptainWutax** [comment]
I looked at the crash report and I can't seem to reproduce the error. I'll get back at you when I find the issue, thanks for the report!

Currently, the mod only supports live MIDI devices, I'll see if I can make it read from MIDI files too. Also, to close a GUI, press ESC.

**Comment by KaptainWutax** [comment]
Issue has been fixed. You can use Beta 0.2.3 or above without crashing :D
